/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by nestjs-trpc.
 * Any manual changes will be overwritten on the next generation.
 *
 * Command: `npx nestjs-trpc generate`
 * Learn more: https://nestjs-trpc.io
 */

import { initTRPC } from "@trpc/server";
import { z } from "zod";

const t = initTRPC.create();
const publicProcedure = t.procedure;
import { todoEntitySchema } from "../entities/todo";
import { createTodoSchema } from "../modules/todo/schema/create-todo.schema";
import { updateTodoSchema } from "../modules/todo/schema/update-todo.schema";

export const appRouter = t.router({
  todo: t.router({
    findAll: publicProcedure
      .output(z.array(todoEntitySchema))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getById: publicProcedure
      .input(z.object({ id: z.string() }))
      .output(todoEntitySchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    create: publicProcedure
      .input(createTodoSchema)
      .output(todoEntitySchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    update: publicProcedure
      .input(z.object({ id: z.string(), data: updateTodoSchema }))
      .output(todoEntitySchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    delete: publicProcedure
      .input(z.object({ id: z.string() }))
      .output(z.object({ success: z.boolean() }))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    })
});

export type AppRouter = typeof appRouter;
